### ISSUE TITLE
Temp email doesn't work anymore, any other solution?

### ISSUE THREAD

**Issue by illidank** [gato-louco/exitlag-account-activator#12]
Looks like exitlag got the mail.tm under black list, i can't use their mail for new account anymore. Do you guys have any alternate method?

**Comment by gato-louco** [comment]
do u mind to look for us a good one?

**Comment by gato-louco** [comment]
yeah, this temp email isn't really work. I don't think they blacklisted it, but I think that they are allowing just some specific email providers, such as google, hotmail, outlook, etc.

**Comment by illidank** [comment]
I did look into some other temp mail before yours, but no luck yet. This is just fine 2 days ago ... i'mma do some reasearch

**Comment by gato-louco** [comment]
I already got a method to activate accounts without need the email confirmation on exitlag, any random email will do. I just need to research how I can manage to bypass the google captcha verification...

**Comment by illidank** [comment]
that sounds wonderful, i'll hold my breath for u

**Comment by minibruce** [comment]
Waiting for your good news bro

**Comment by gato-louco** [comment]
Yeah, just wondering if it is really worth to share this method publicly, cuz Exitlag is surely seeing this project and they could fix it as soon as I share it...

**Comment by minibruce** [comment]
Different people have different opinions on this question. It depends on where you think about it. 
The program always has bugs. Myabe you can think of it as a challenge. If you want to share, then do it.

**Comment by gato-louco** [comment]
I don't even use exitlag, but it is pretty annoying when people come to my DM and beg for an update cuz they have so much lag....
Anyway, maybe tomorrow I make a tutorial about this new method to create accounts (not activate, cuz it remains the same way).

**Comment by minibruce** [comment]
You helped a lot of poor people. They should thank you

**Comment by illidank** [comment]
> I don't even use exitlag, but it is pretty annoying when people come to my DM and beg for an update cuz they have so much lag....
> Anyway, maybe tomorrow I make a tutorial about this new method to create accounts (not activate, cuz it remains the same way).

great news in these dark time (cuz of covid, not cuz of exitlag)

**Comment by DanielJames3113** [comment]
I've tried a gmail generator and it still doesn't work, I think exitlag actually has to verify an email some how

**Comment by cliffrochie** [comment]
I tried creating a new gmail. it successfully generate a three day trial, but when I run it, it won't work. The exitlag automatically disable the tunneling.

**Comment by DanielJames3113** [comment]
I think I might have found a way, but I'll need to do further testing tho

**Comment by DanielJames3113** [comment]
So this is my method of creating an account:
1.Go to this website: https://generator.email/blog/gmail-generator
2.Put in an email in the given box and click generate ( I haven't tried with a temp mail tho, I used my actual email)
3.Make an Exitlag account as normal with any emails given in the bigger box below( the confirm email that Exitlag send will be sent to the inbox of the email you have insert in step 2
4.Use gatolouco's account activator to activate the Exitlag account you have just just created
Enjoy :D
If there is any problem just hit me up, I'll try my best to help

*Note: I do NOT own this website and I do NOT know the owner of this website.

**Comment by illidank** [comment]
> So this is my method of creating an account:
> 1.Go to this website: https://generator.email/blog/gmail-generator
> 2.Put in an email in the given box and click generate ( I haven't tried with a temp mail tho, I used my actual email)
> 3.Make an Exitlag account as normal with any emails given in the bigger box below( the confirm email that Exitlag send will be sent to the inbox of the email you have insert in step 2)
> 4.Use gatolouco's account activator to activate the Exitlag account you have just just created
> Enjoy :D
> If there is any problem just hit me up, I'll try my best to help
> 
> *Note: I do NOT own this website and I do NOT know the owner of this website.

this actually works, i don't know that dot does not matter in gmail ... lol

**Comment by minibruce** [comment]
> So this is my method of creating an account:
> 1.Go to this website: https://generator.email/blog/gmail-generator
> 2.Put in an email in the given box and click generate ( I haven't tried with a temp mail tho, I used my actual email)
> 3.Make an Exitlag account as normal with any emails given in the bigger box below( the confirm email that Exitlag send will be sent to the inbox of the email you have insert in step 2)
> 4.Use gatolouco's account activator to activate the Exitlag account you have just just created
> Enjoy :D

dot is really no mater in gmail. 
Maybe this is a temporary solution. 
I think got-louco's bypassing verification is a great way
excited

**Comment by minibruce** [comment]
it has some issuses
4 dots the most

**Comment by DanielJames3113** [comment]
> it has some issuses
> 4 dots the most

I have tried out one email but I remember the account I use had a lot of dots tho, sorry for not remembering the exact number, but still this is just a temporary solution while we wait for gatolouco's method

**Comment by minibruce** [comment]
> > it has some issuses
> > 4 dots the most
> 
> I have tried out one email but I remember the account I use had a lot of dots tho, sorry for not remembering the exact number, but still this is just a temporary solution while we wait for gatolouco's method

we are all waiting....
but this can solve the urgent need
thx anyway

**Comment by gato-louco** [comment]
> dot is really no mater in gmail
ow, yeah, there is also it.
I think it is a better solution for now, I had forgot to told you guys about that :smile:  

https://tio.run/##PYxBCsIwEEX3XiQzZAzqPuI9RCTGSR1JmtK0BhHPHtuNq/948P7TvVzxowzTts93bsE2SMQk5NEeP/UhkSGd5YLVJlPmW5lG2JGgVkbpvxEkD1UzUoC65vqwHCyjv5sWQL3zPF45OYmK1KlbwficFO3J577kyCbmDtsP

**Comment by gato-louco** [comment]
credits to https://codegolf.stackexchange.com/questions/204473/generate-gmail-dot-aliases

**Comment by minibruce** [comment]
great !
hope everyone keep a low profile plz.

**Comment by adnrussg** [comment]
Hello what is the new method? I did not understand the links. Any replies would be great.

**Comment by gato-louco** [comment]
@adnrussg unfortunately, you don't attend to a essential requisite, a 🧠.

**Comment by minibruce** [comment]
A Brain

**Comment by gato-louco** [comment]
Looks like we got a new solution to this problem. For now, I am closing this issue as solved.

**Comment by DanielJames3113** [comment]
looks like this method has been patched, can someone try it out?

**Comment by Vinh1984** [comment]
I have done it successfully but have to create a new account with gmail to be able to repeat the 3 day trial. Thank you very much Gatolouco!

**Comment by Vinh1984** [comment]
> Có vẻ như chúng tôi đã có một giải pháp mới cho vấn đề này. Hiện tại, tôi đang kết thúc vấn đề này như đã được giải quyết.

vậy là hiện tại tôi phải làm sao ? Có cách nào sử dụng 1 thư không cần tạo thư mới không ?

**Comment by mahnader** [comment]
gmail generator dont work

**Comment by Vinh1984** [comment]
thanks very much
________________________________

**Comment by HatsuneMiku94** [comment]
not working anymore, even using legit gmail accounts , different ip, a VM, etc... you get logged out after 3 to 5 mins from creating a fresh account and then you have 0 days.

**Comment by gato-louco** [comment]
> 
> 
> not working anymore, even using legit gmail accounts , different ip, a VM, etc... you get logged out after 3 to 5 mins from creating a fresh account and then you have 0 days.

check #26
