### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Kapparyder** [gato-louco/exitlag-account-activator#13]
5th september 2021 and does not seem to be working. Am i doing something wrong? or is it patched?

**Comment by sawryy** [comment]
It seems like the patched that temp mail from working. Seems to work if you make your own email.

**Comment by HereComesDatBoii** [comment]
Im using gmail as my mail and its not working for me

**Comment by Kapparyder** [comment]
Its not working with my gmail either.

**Comment by rikidevdroid** [comment]
I installed python 3.9 and correctly installed "pip install websockets" but when I run the main.py I get this error:
line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by gato-louco** [comment]
Check issue #12 . There is a bypass to it :)
