### ISSUE TITLE
Different password

### ISSUE THREAD

**Issue by Jqfet** [gato-louco/exitlag-account-activator#14]
Any way to use a different password?

**Comment by gato-louco** [comment]
Yes, there is. I would need to reverse engineering exitlag again. contact me via email gatoloucooficial@protonmail.com; (I would charge a value for the service, around $100)

**Comment by lujiangz** [comment]
You can create a new password after you md5 your password, but I don't know about the key that will be added to the sequel. I don't know if it is related to the password.

**Comment by gato-louco** [comment]
There is a secret key that is added in the hash, the only way to get the key is by reverse engineering it. if @Jqfet wants, I could do it, but it would take me some time... feel free to send me an email
