### ISSUE TITLE
????

### ISSUE THREAD

**Issue by castgarlicbread** [gato-louco/exitlag-account-activator#15]
i type the email and it sends things but doesn't activate the trail

**Comment by iHafez** [comment]
its working for me try to close exitlag before activating the email
and try to active the account from the email that exitlag sent to you

**Comment by Agmaromatic** [comment]
It's working as of 09/25/21 maybe you're doing something wrong

**Comment by gato-louco** [comment]
As appointed by @iHafez and @Agmaromatic, it does work.
Read the readme.md file carefully.

**Comment by castgarlicbread** [comment]
ty it worked
