### ISSUE TITLE
websockets installed, account made, a week later, run mainpy and no extra days 

### ISSUE THREAD

**Issue by GitHubForumLurker** [gato-louco/exitlag-account-activator#16]
went to try and use it today and my normal 3 day expired, ran main, put email in, email has required password, the cmd throws a bunch of code and closes, no extra 3 days

**Comment by GitHubForumLurker** [comment]
![main py result](https://user-images.githubusercontent.com/91622903/135308107-4819d648-6526-4af7-be92-fbbbff1e8dfe.png)

**Comment by gato-louco** [comment]
Check #15 14h ago someone told it is working.

> cmd throws a bunch of code and closes

This is expected. Check if you haven't already activated this account.

**Comment by GitHubForumLurker** [comment]
are u not supposed to verify it or anything?

**Comment by gato-louco** [comment]
Aren't u supposed to have a brain?

**Comment by gato-louco** [comment]
I am supposed to do nothing. I am literally giving it for free and you also want free support? 

Damn, you haven't any notion, boy...

**Comment by gato-louco** [comment]
#17  working.
