### ISSUE TITLE
Did not work for me

### ISSUE THREAD

**Issue by Amin52728** [gato-louco/exitlag-account-activator#17]
Hello
I did all the steps you mentioned but this script worked for first time but it does not work for second time.
Do I have to create a new account again in ExitLag?

**Comment by gato-louco** [comment]
Of course you do.

**Comment by Amin52728** [comment]
Worked for me
Thank you for your hard work🙏🏻

**Comment by Amin52728** [comment]
> Of course you do.

Worked for me
Thank you for your hard work🙏🏻
