### ISSUE TITLE
Error with websockets

### ISSUE THREAD

**Issue by Ty6ukTV** [gato-louco/exitlag-account-activator#3]
Error with websockets. Maybe i am noob, but i tried all methods, for fix it, but nothing help me. Maybe you can fix it? (because i really wanna use ExitLag. Or give me advice)

**Comment by itsOwen** [comment]
it works fine for me I just tested it like 2 minutes ago

make sure u have done pip install websockets

**Comment by gato-louco** [comment]
I forgot to add it to the how to use.

On CMD, type `pip install websockets` it should work.

**Comment by Ty6ukTV** [comment]
> I forgot to add it to the how to use.
> 
> On CMD, type `pip install websockets` it should work.

Yes thanks, it's working.
