### ISSUE TITLE
question about activator and hwid

### ISSUE THREAD

**Issue by wankio** [gato-louco/exitlag-account-activator#32]
so i'm just using it, click twice, at first time it dont, but at 2nd time it work, when i'm restart it just have bsod 0xc000001
if i'm remember you should not install exitlag on system drive(C) right ?

**Comment by deadzeat** [comment]
you can complete instructions?

**Comment by gato-louco** [comment]
>  if i'm remember you should not install exitlag on system drive(C) right ?

doesn't matter.

bypass needs update btw, check #26
